backend:
  name: git-gateway
  branch: main

media_folder: "ss/uploads"
public_folder: "/ss/uploads"

collections:
  - name: "movies"
    label: "Movies"
    folder: "movies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Download Link", name: "download", widget: "string" }
      - { label: "Thumbnail", name: "image", widget: "image" }
