backend:
  name: git-gateway
  branch: main

media_folder: "ss"
public_folder: "/ss"

collections:
  - name: "movies"
    label: "Movies"
    folder: ""
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }