backend:
  name: git-gateway
  branch: main

media_folder: "ss" # your screenshots folder
public_folder: "/ss"

collections:
  - name: "movies"
    label: "Movies"
    folder: "movies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Language", name: "language", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Download Link 480p", name: "link480", widget: "string" }
      - { label: "Download Link 720p", name: "link720", widget: "string" }
      - { label: "Download Link 1080p", name: "link1080", widget: "string" }
      - { label: "Screenshots", name: "screenshots", widget: "list", field: {label: "Image", name: "image", widget: "image"} }
