backend:
  name: git-gateway
  branch: main

media_folder: "ss"
public_folder: "/ss"

collections:
  - name: "movies"
    label: "Movies"
    folder: "movies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Download Links", name: "links", widget: "list", fields: [
            { label: "Label", name: "label", widget: "string" },
            { label: "URL", name: "url", widget: "string" }
        ] }
